In [48]:
import pandas as pd
import numpy as np
from statistics import mode

In [6]:
df = pd.read_csv('iphone_purchase_records.csv')
df = df.drop(columns = ['Gender'],axis = 1)
df

     Age  Salary  Purchase Iphone
0     19   19000                0
1     35   20000                0
2     26   43000                0
3     27   57000                0
4     19   76000                0
..   ...     ...              ...
395   46   41000                1
396   51   23000                1
397   50   20000                1
398   36   33000                0
399   49   36000                1

[400 rows x 3 columns]

In [32]:
x = df.drop(columns = ['Purchase Iphone'],axis = 1)
y = df['Purchase Iphone']

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchase Iphone, Length: 400, dtype: int64

In [67]:
# euc_dist = lambda a1,b1,a2,b2: np.sqrt((a2-a1)**2 + (b2-b1)**2)

euc_dist = lambda pt1,pt2 : np.sqrt( (pt1[0] - pt2[0])**2 + (pt1[1] - pt2[1])**2 )


class KNN:
    def __init__(self,k):
        self.k = k

    def fit(self,xtrain,ytrain):
    
        self.xtrain = xtrain
        self.ytrain = ytrain
        

    def predict(self,xtest):
        
        majority_vote = []                                                               
        for i in range(len(xtest)):                                      
            dist_store = [( euc_dist(xtest.iloc[i],self.xtrain.iloc[j]),self.ytrain.iloc[j] )\
                            for j in range(len(self.xtrain))]
            dist_store = sorted(dist_store, key=lambda x: x[0])
            majority_vote.append( mode([d[1] for d,z in zip(dist_store,range(self.k))]) )
        
        return majority_vote

In [71]:
test = KNN(3)
test.fit(x[:100],y[:100])
farris = test.predict(x[100:200])

[0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [74]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x[:100],y[:100])
real = neigh.predict(x[100:200])

In [75]:
farris == real

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])